[[reactions]]
# mintkk
keywords = ['민트', '민초', '초민', '먹자']
answers = [
	'다른 것은?', '딴 건?', '다른거는?', '다른건?', '다른 건?', '아...아오이?', 'A0001', '니나 마~이 쳐 무라', '민트? 정신 나간거 아이가',
	'아오이가 좋아하겠다', '아오이가 좋아할끼다', '고마해라',
] # 0001: 아...아오이... / 아...아오이? / 아...아오이... 언니ㄴ

[[reactions]]
# genius
keywords = ['천재', '뭐,', '최고', '체고', '니까']
answers = ['응?', '응...?', '응...............................?', '...']

[[reactions]]
# eee
keywords = ['에에', 'ㅔㅔ', '에ㅔ', 'ㅔ에', ' ??']
answers = ['?????', '알긋냐', '뭐여']

[[reactions]]
# rate
keywords = ['뭐', '될', '되', '된', '할', '생각', '어때', '?', '어떤', '그치', '그렇', '있었']
answers = [
	# good
	'참말로 괘안은데?', '괘안은데?', '알긋다', '알긋다(감명)', '알긋다(통찰)', '알긋다(달관)', '알긋다(박식)', '알긋다(천하무쌍)', '개안지 않나?', '글켔다', 'ㅇㅇ', '👍',
	'응', '응', '응', '응', '응', 
	# seyana (normal)
	'그렇구나', '고렇구나', '고거는...', '이거는...',
	'Seyana...', 'Soyana...', 'Sorena...', 'Arena...', 
	':seyana: 그렇구나', ':akane: ...',
	# bad
	'파이다', '별로다', '증말 별로다', '등신이가', '모르겠다(진심)', '모르겠다(통찰)', '모르겠다(달관)', '모르겠다(멍청)', 
	'파이지 않나?', '이상하다', '치아뿌라 그거', '치아뿌라', '치아뿌라 인터넷', '치아뿌라', '등신 아이가', 'ㄴㄴ', '👎', '빙시이가', '치아라', 
	# etc
	'딴 건?', '그런 건 모르겠다는 걸~', '모르겠다', '모르겠단걸~',
]

[[reactions]]
# idea
keywords = ['떠올']
answers = ['뭐고?', '맞나?', '문데?']

[[reactions]]
# listen
keywords = ['들어', '있잖', '키이', '테요']
answers = ['응?', '뭐여', '와그라노', '문디']

[[reactions]]
# call
keywords = ['아카네', 'kane', '야 ', '야! ']
answers = ['응?', '응', '뭐고?', '응', '불렀나?', '와?', '뭐여?', '와그라노?']
